name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Installation
  
  To install this version, use the following command:
  ```shell
  docker extension install cedricziel/dd-extension-lgtm:v$RESOLVED_VERSION
  ```
  
  ## Changes

  $CHANGES
